config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  
  devise_for :users
  resources :users
  resources :albums
  resources :photos
end

app/models/album.rb
class Album < ActiveRecord::Base
    has_many :photos, :dependent => :destroy
    belongs_to :user
    accepts_nested_attributes_for :photos
    validates :title, presence: true #Wymagany tytul albumu
    validates :is_private, inclusion: [true, false]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  
  #Wymagany tytul zdjecia
  validates :title, :file, presence: true 
  
  #Zalacznik i walidacja zalacznika
  has_attached_file :file, styles: {large: "1000x1000>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment :file, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }, size: { in: 0..5.megabytes }
  validates :is_private, inclusion: [true, false]
  
  #Asocjacje
  belongs_to :album
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :email, uniqueness: true
  validates :password, length: { minimum: 6 }
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :photos, :dependent => :destroy
  has_many :albums, :dependent => :destroy
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  
before_action :authenticate_user!, only: [:new, :edit, :delete]
  
  def index
    @albums = current_user.albums.all
  end
  
  def show
    @album = Album.find(params[:id])
  end
  
  def new
    @album = current_user.albums.build
  end

  def create
    @album = current_user.albums.build(album_params)
    if @album.save
      redirect_to @album
    else
      render :new
    end
  end
  
  def edit
    find_album
  end

  def update
    find_album

    if @album.update_attributes(album_params)
      redirect_to @album
    else
      render :edit
    end
  end
  
  def destroy
    find_album
    @album.photos.destroy
    @album.destroy
    redirect_to albums_path
  end
  
  private
  
  def find_album
     @album = Album.find(params[:id])
  end
  
  def album_params
    params.require(:album).permit(:title, :is_private)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def after_sign_in_path_for(resource) #Po zalogowaniu kieruje do strony zd zdjęciami uzytkownika
    photos_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

before_action :authenticate_user!, only: [:new, :edit, :delete]

 def index
   @photos = current_user.photos.all
 end
  
  def show
    find_photo
  end

  def new
    @photo = current_user.photos.new
  end

  def create
    @photo = current_user.photos.new(photo_params)
    if @photo.save
      redirect_to @photo
    else
      render :new
    end
  end

  def edit
    find_photo
  end

  def update
    
    find_photo

    if @photo.update_attributes(photo_params)
      redirect_to @photo
    else
      render :edit
    end
  end
  
  def destroy
    find_photo
    @photo.destroy
    redirect_to photos_path
  end

  private
  
  def find_photo
    @photo = Photo.find(params[:id])
  end
  
  def photo_params
    params.require(:photo).permit(:title, :file, :album_id, :is_private)
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    before_action :authenticate_user!, only: [:index, :destroy]
    
    def index
      @users = User.all
    end
    
    def destroy
      @user = User.find(params[:id])
      @user.destroy
      redirect_to users_path
    end

end

app/helpers/albums_helper.rb
module AlbumsHelper
    def count_albums(albums)
        if (albums.count == 0) 
            return "Nie stworzyłeś jeszcze żadnych albumów :("
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
    #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
  def have_title(photo)
    if @photo.album_id
      return Album.find(@photo.album_id).title
    else
      return "Nie dodano do albumu" 
    end
  end
  
  def count_photos(photos)
        if (photos.count == 0) 
            return "Nie dodałeś jeszcze żadnych zdjęć! :("
        end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.erb
<%= form_for @album do |f| %>
      <div class="form-group">
        <%= f.label :title, "Tytuł albumu" %> <br>
        <%= f.text_field :title, placeholder: "Wpisz tytuł", class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :is_private, "Album prywatny?" %> <br>
        <%= f.radio_button :is_private, 'true' %> Tak
        <%= f.radio_button :is_private, 'false' %> Nie
      </div>
      
      <div class="form-group">
        <%= f.submit 'Zapisz', class: "btn btn-primary" %>
        <%= link_to 'Anuluj', @album, class: "btn" %>
      </div>
      
<% end %>

app/views/albums/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col col-sm-4"
            <h1>Edytuj album:</h1>
            <%= render 'form' %>
            </div>
            </div>
</div>

app/views/albums/index.html.erb
<div class="container">
    <div class="row">
        <div class="col col-sm-10">
<%= count_albums(@albums) %>

<% @albums.each do |album| %>

  <div>
    <%= link_to [album] do %>
      <h2><%= album.title %></h2>
    <% end %>
    
    <% if (album.photos.count > 0) %>
      <%= image_tag album.photos.first.file(:medium), class: "img-responsive" %>
    <% end %>
    <p>Dodano <%= album.created_at.strftime("%d"+"."+"%m"+"."+"%Y") %></p>
    <p>Ilość zdjęć w albumie: <%= album.photos.count %></p>
  </div>
<% end %>

</div>
</div>
</div>

app/views/albums/new.html.erb
<div class="container">
    <div class="row">
        <div class="col col-sm-4">
    <h1>Dodaj nowy album:</h1>
    <%= render 'form' %>
</div>
</div>
</div>

app/views/albums/show.html.erb
<% content_for :page_title do @album.title end %>

<div class="container">
  <div class="row">
    <div class="col-sm-12">
    <% if ((@album.is_private? && !user_signed_in?) || (@album.is_private? && current_user.id != @album.user_id)) %>
      <p>Nie masz uprawnień do oglądania tego albumu!</p>
    <% else %>
      <h1 class="page-header"><%= @album.title %></h1>
      
      <%- if (user_signed_in? && current_user.id == @album.user_id) %>
        <%= link_to 'Edytuj album', edit_album_path(@album), class: "btn btn-primary" %>
        <%= link_to 'Usuń album', album_path, method: :delete, data: {confirm: "Czy jesteś pewien?"}, class: "btn btn-warning" %>
      <% end %>
      
      <p><b>Dodano:</b> <%= @album.created_at.strftime("%d"+"."+"%m"+"."+"%Y") %></p>
      <p><b>Ilość zdjęć w albumie: </b><%= @album.photos.count %></p>
      <p><b>Link do albumu: </b><%= request.original_url %></p>
      <p><b>Prywatny? </b><%= @album.is_private ? "Tak." : "Nie." %></p>
      
      <% @album.photos.each do |photo| %>
        <div class="col-lg-3 col-md-4 col-xs-6 thumb">
        <%= link_to photo, class: "thumbnail" do %>
          <%= image_tag photo.file.url(:medium), class: "img-responsive" %>
        <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
</div>

app/views/layouts/_footer.erb
<footer class = "footer">
    <br>
    <p>Snapshot - Michał Chojecki - 2016/2017</p>
</footer>

app/views/layouts/_header.erb
<nav class="navbar navbar-default navbar-static-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Snapshot", root_path, class: 'navbar-brand', id: "logo" %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
          <%- if user_signed_in? %>
              <% if current_user.admin? %>
                <li><%= link_to 'Użytkownicy', users_path, class: "red" %></p>
              <% end %>
              <li><%= link_to 'Stwórz album', new_album_path %></p>
              <li><%= link_to 'Dodaj zdjęcie', new_photo_path %></p>
              <li><%= link_to 'Twoje albumy', albums_path %></p>
              <li><%= link_to 'Twoje zdjęcia', photos_path, class: "active" %></p>
              <li><%= link_to "Wyloguj (#{current_user.email})", destroy_user_session_path, :method => :delete %></li>
          <%- else %>
              <li><%= link_to 'Zaloguj', new_user_session_path  %></li>
              <li><%= link_to 'Zarejestruj się', new_user_registration_path  %></li>
        <% end -%>
          </ul>
        </div>
      </div>
    </nav>

app/views/layouts/_messages.html.erb
<div class="container">
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <title>
      <% if content_for? :page_title %>
        <%= yield :page_title %> – Snapshot
      <% else %>
        Snapshot
      <% end %>
    </title>
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%=render 'layouts/footer' %>
  
  </body>
</html>

app/views/pages/index.html.erb
<div class="container">
      <div class="jumbotron" id="tablica">
        <h1> Witaj w serwisie Snapshot!</h1>
        <p>Serwis Snapshot jest to aplikacja napisana jako temat pracy inżynierskiej na WSB w Dąbrowie Górniczej</p>
        <p>Aplikacja została napisana we frameworku Ruby on Rails.</p>
        <p>Funkcjonalności:</p> 
        <p>(tworzenie i usuwanie, konto admina), rejestracja (sprawdzanie błędów przy rejestracji, zmiana hasła przez link w e-mailu)</p>
        <p>Dodawania, usuwanie, edytowanie albumów i zdjęć(konwersja do 3 roździelczości)</p>
        <p>Albumy i zdjęcia z opcją is_private</p>
        <p>Stylizacja frameworkiem Bootstrap</p>
        <p>I inne...</p>
        <%= link_to "Zarejestruj się!", new_user_registration_path, class: "btn btn-lg btn-success" %>
      </div>

    </div>

app/views/photos/_form.html.erb
<%= form_for @photo, html: { :multipart => true } do |f| %>
  <div class="form-group">
    <%= f.label :title, 'Tytuł zdjęcia' %> <br>
    <%= f.text_field :title, placeholder: "Wpisz tytuł", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :file, 'Plik' %> <br>
    <%= f.file_field :file, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :album %> <br>
    <%= collection_select(:photo, :album_id, current_user.albums, :id, :title, {prompt: 'Wybierz album'}, {class: "form-control"})%>
  </div>
  
  <div class="form-group">
    <%= f.label :is_private, "Prywatne?" %> <br>
    <%= f.radio_button :is_private, 'true' %> Tak
    <%= f.radio_button :is_private, 'false' %> Nie
  </div>
  
  <div class="form-group">
    <%= f.submit 'Zapisz', class: "btn btn-primary"%>
    <%= link_to 'Anuluj', @photo, class: "btn" %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<div class="container">
     <div class="row"></div>
        <div class="col col-sm-4">
    <h1>Edytuj zdjęcie </h1>
    Aktualne zdjęcie: <br>
    <%= image_tag @photo.file.url(:medium) %>
    
    <%= render 'form' %>
    </div>
    </div>
</div>

app/views/photos/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">Galeria Twoich zdjęć</h1>
    </div>
    
    <%= count_photos(@photos) %>

    <% @photos.each do |photo| %>
      <div class="col-lg-3 col-md-4 col-xs-6 thumb">
        <%= link_to photo, class: "thumbnail" do %>
          <%= image_tag photo.file.url(:medium), class: "img-responsive" %>
        <% end %>
      </div>
    <% end %>

  </div>
</div>

app/views/photos/new.html.erb
<div class="container">
    <div class="row">
        <div class="col col-sm-4">
    <h1>Dodaj nowe zdjecie</h1>
    <%= render 'form' %>
    </div>
    </div>
    </div>

app/views/photos/show.html.erb
<div class="container">
  <div class="row">
        <div class="col col-sm-4">
  <% content_for :page_title do @photo.title end %>
  
  <% if ((@photo.is_private? && !user_signed_in?) || (@photo.is_private? && current_user.id != @photo.user_id)) %>
    <p>Nie masz uprawnień do oglądania tego zdjęcia!</p>
  <% else %>
    <h2>Tytuł: <%= @photo.title %></h2>
    <p><b>Album:</b> <%=have_title(@photo) %></p>
    <p><b>Dodano:</b> <%= @photo.created_at.strftime("%d"+"."+"%m"+"."+"%Y") %></p>
    <p><b>Prywatny? </b><%= @photo.is_private ? "Tak." : "Nie." %></p>
    <p>
      <a href = "<%= URI.join(request.url, @photo.file.url) %>">Bezpośredni link do zdjęcia</a>
    </p>
    <%= image_tag @photo.file.url(:large), class: "img-responsive" %> <br>
    
    <%- if (user_signed_in? && (current_user.id == @photo.user_id)) %>
      <%= link_to 'Edytuj', edit_photo_path(@photo), class: "btn btn-primary" %>
      <%= link_to 'Usuń', photo_path, method: :delete, data: {confirm: "Czy jesteś pewien?"}, class: "btn btn-warning" %>
    <% end %>
  <% end %>
</div>
</div>
  </div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <% if current_user.admin? %>
    <div class="col-sm-10">
      <h1 class="page-header">Użytkownicy</h1>
    </div>

        <% @users.each do |user| %>
        <div class ="row">
            <div class="col-sm-10">
            <p><b>Nazwa użytkownika: </b><%= user.email %></p>
            <p>Utworzony: <%= user.created_at.strftime("%d"+"."+"%m"+"."+"%Y") %></p>
            <p>Ilość zdjęć: <%= user.photos.count %></p>
            <p>Ilość albumów: <%= user.albums.count %></p>
            
               <p><%= link_to 'Usuń użytkownika', user, method: :delete, data: {confirm: "Czy jesteś pewien? Usunięte zostaną również zdjęcia i albumy tego użytkownika! #{user.email}"}, class: "btn btn-danger" %></p>
            </div>
        </div></br>
        <% end %>
    <% else %>
    <p>Nie masz uprawnień do oglądania tej strony!</p>
    </div>
    <% end %>
      </div>
  </div>